import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Hero from '../components/landing/Hero'
import Features from '../components/landing/Features'
import Subscribe from '../components/landing/Subscribe'
import Pricing from '../components/landing/Pricing'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Meet with wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <Hero />

        <Subscribe />

        <Features />

        <Pricing />

      </main>


    </div>
  )
}

export default Home
