import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { fetchAccountMeetings } from '../utils/calendar_manager'
import { loginWithWallet } from '../utils/user_manager'
import Hero from '../components/landing/Hero'
import Features from '../components/landing/Features'
import Subscribe from '../components/landing/Subscribe'
import Pricing from '../components/landing/Pricing'

const getMeetings = async () => {
  const account = await loginWithWallet()
  console.log(await fetchAccountMeetings(account.address))

}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <Hero />

        <Subscribe />

        <Features />

        <Pricing />

      </main>


    </div>
  )
}

export default Home
