import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import { fetchUserMeetings, scheduleMeeting } from '../utils/calendar_manager'
import { getMeeting } from '../utils/database'
import { loginWithWallet } from '../utils/wallet'

const getMeetings = async () => {
  const user = await loginWithWallet()

  console.log(await fetchUserMeetings(user))
}

let a = ''

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <button onClick={getMeetings}>Get meetings</button>


      </main>


    </div>
  )
}

export default Home
