name: push.yml
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'pre-prod'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get last two commit messages
      id: last_commits
      run: |
        echo "COMMIT_MSGS=$(git log -2 --pretty=format:'%s' | paste -sd ' | ' -)" >> $GITHUB_ENV

    - name: Send Discord Notification
      if: always()
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_AVATAR: "https://res.cloudinary.com/dun8bju7q/image/upload/v1753807987/mw-socials_3_evlwta.png"
        DISCORD_MENTIONS: '{ "users": ["976068042318569482", "615959113586835476"] }'
      with:
        args: |
          <@976068042318569482> <@615959113586835476>
          🚀 **Deployment Completed**
          
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref_name }}
          **Environment:** ${{ github.ref == 'refs/heads/main' && 'Production' || github.ref == 'refs/heads/develop' && 'Preview' || github.ref == 'refs/heads/pre-prod' && 'Pre-prod' || 'Unknown' }}
          **Status:** ${{ job.status }}
          **Commit:** ${{ github.sha }}
          **Author:** ${{ github.actor }}
          **Workflow:** ${{ github.workflow }}
          **Last 2 Commits:** ${{ env.COMMIT_MSGS }}
          
          View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
